### ISSUE TITLE
Add icons for appropriate form fields.

### ISSUE THREAD

**Issue by b-cheek** [b-cheek/ChordCaptain#9]
- [ ] Clef
- [ ] Key Signature (See Issue #3)
- [ ] Time Signature (See Issue #2)
- [ ] Range (see Issue #8)
- [ ] Instrument (See Issue #5)
- [ ] Rhythm
